samvera/browse-everything

- README.md
- lib/browse_everything.rb
- lib/browse_everything/driver/dropbox.rb
- lib/generators/browse_everything/config_generator.rb
- lib/generators/browse_everything/templates/browse_everything_providers.yml.example
- spec/fixtures/vcr_cassettes/dropbox.yml
- spec/spec_helper.rb
- spec/unit/browser_spec.rb
- spec/unit/dropbox_spec.rb
This may be somewhat pedantic, and I will grant you that, but I originally looked into this because I couldn't figure out why I was seeing "Drop Box" in the dropdown for cloud providers. Turns out it was coupled to the name of the driver, so I figured I'd just go through the codebase and refer to Dropbox consistently as "Dropbox."
> Dropbox should be called 'Dropbox'

- Rakefile
- app/assets/javascripts/browse_everything/behavior.js.coffee
- app/views/browse_everything/_file.html.erb
- app/views/browse_everything/_files.html.erb
- browse-everything.gemspec
- spec/javascripts/behavior_spec.js
- spec/javascripts/helpers/jasmine-jquery.js
- spec/javascripts/jasmine_spec.rb
- spec/javascripts/support/jasmine.yml
- spec/javascripts/support/jasmine_helper.rb
- spec/spec_helper.rb
- spec/support/rake.rb
- spec/views/browse_everything/_file.html.erb_spec.rb
This adds support for selecting all files in a directory. Selecting a checkbox will descend into each subfolder, loading it, and selecting its files.
> Use checkbox to select all files

- .travis.yml
- app/assets/javascripts/browse_everything.js
Using bootstrap concatenates all the files, and most external libraries
instead individually include each necessary piece of JS. If
browse-everything uses bootstrap without the "-sprockets", Bootstrap' JS
effectively gets included twice.
> Use bootstrap-sprockets instead.

- app/controllers/browse_everything_controller.rb
- spec/helper/browse_everything_controller_helper_spec.rb
During regression testing we noticed that although dropbox was now working box was not allowing connections.  This commit allows for one state to be added to the url, and adds a test to be certain there is a state for box and dropbox providers.
> Optionally adding state to url so box and dropbox will work

- app/assets/javascripts/browse_everything/behavior.js.coffee
In certain situations, the `$(obj).browseEverything()` call might get triggered before the auto-toggled initialization caused by `<button data-toggle="browse-everything"... />`. If that happens, the promise object returned by the `browseEverything()` call gets wiped out later during auto-toggle initialization. This change does two things:
1. Causes manual init to include the auto-toggle parameters _if the target hasn't been initialized yet_.
2. Skips auto-toggle init _for any target that's already been manually initialized_.
IOW, whichever init happens first will handle the toggle parameters, and auto-toggle will only happen if it needs to.
> Don't wait for auto-toggle if the explicit browseEverything() call is seen first.

- app/assets/javascripts/browse_everything/behavior.js.coffee
28395bc introduced code to avoid re-initializing an already-initialized browse context, but the placeholder it used now prevents initialization if the consumer passes in a `context` option.
> Rename data('context') to data('ev-state') to avoid init-time collision with context option.

- app/controllers/browse_everything_controller.rb
I'm not sure if this is entirely necessary, or even if it might break things. If your base application is already doing this, what happens if you include an engine that does as well?
Someone notified us that not including this was a security flaw, which is technically true I think, but only if you're using this gem alone and not within the context of another Rails application which (ostensively) would be guarding against these attacks.
Thoughts? @jkeck @jcoyne @jeremyf
> Guard against cross-site scripting attacks

- app/assets/javascripts/browse_everything/behavior.js.coffee
- app/assets/stylesheets/browse_everything/_browse_everything.scss
- app/views/browse_everything/_file.html.erb
This allows directories with long names to properly truncate the same way as files.
Additionally, the scss and view code was cleaned up for better readability.
> Set size of container columns

- app/assets/javascripts/browse_everything/behavior.js.coffee
- app/assets/stylesheets/browse_everything/_browse_everything.scss
- app/views/browse_everything/_files.html.erb
- app/views/browse_everything/index.html.erb
Progress bar doesn't work within a modal, so this displays text with a faded background.
> Add visual changes when waiting for provider responses

- .rubocop.yml
- README.md
- lib/browse_everything/browser.rb
- lib/browse_everything/driver/s3.rb
- lib/generators/browse_everything/templates/browse_everything_providers.yml.example
- spec/unit/s3_spec.rb
Changes in this commit:
* Adheres to the conventions for AWS' [cross-SDK configuration defaults](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/).
* Adds an `:s3_uri` output format (`s3://bucket_name/path/to/file`) in addition to public and signed URLs.
* Deprecates the `:signed_url` config option in favor of `:response_type` to accommodate the S3 URI option.
> Amazon S3 driver enhancements

- README.md
- app/assets/javascripts/browse_everything.js
Instead we'll expect the host app to provide this dependency.
This allows the host app to switch jquery versions (from 1 to 2 or 3)
Fixes #163
> Stop explicitly requiring jquery

- .rubocop_todo.yml
- lib/browse_everything/retriever.rb
Forces `httparty` to stream any http(s) file larger than 500mb instead of reading it all into memory. See the `httparty` docs [here](https://github.com/jnunemaker/httparty/blob/d9c4067a9c70c6129146cb6db0ab48d32e0e8494/lib/httparty.rb#L42).
> Set stream_body option to true for http(s) files larger than 500MB

- app/views/browse_everything/_files.html.erb
Box has a feature that acts like symlinks, and it symlinked directories as regular files (not containers) with nil file size. There's no good way for BE to handle them, so let's at least not error on them.
> Skip files with nil size

- browse-everything.gemspec
- lib/browse_everything/driver/s3.rb
This is possible due to the refactoring of aws-sdk, which was released
as version 3.0
> Only require the parts of the aws-sdk that we need (s3)

- .rubocop.yml
- app/controllers/browse_everything_controller.rb
- lib/browse_everything/auth/google/request_parameters.rb
- spec/controllers/browse_everything_controller_spec.rb
Also modifies the default sorting for file entries returned from the Google Drive API
> Provides remedy for cases where Google Drive auth tokens must be forcibly cleared

- app/views/browse_everything/_files.html.erb
- lib/browse_everything/driver/file_system.rb
- spec/unit/browse_everything/driver/file_system_spec.rb
This was found to break the treetable jQuery plugin within a Valkyrie repository integrating this Gem.  As the relative paths for parent directories are redundant (the directories to which these resolve are also featured on the interface), this only affects the usability of the interface
> Removing the rendering of relative paths to current and parent directories within the `FileSystem` Driver

- .rubocop.yml
- lib/browse_everything.rb
- lib/browse_everything/browser.rb
- lib/browse_everything/driver/base.rb
- spec/unit/browse_everything/browser_spec.rb
Ensures backward compatibility for clients accessing the configuration options using strings as keys
> Ensures that the `BrowseEverything` configuration is a `ActiveSupport::HashWithIndifferentAccess` rather than a `Hash`

- lib/generators/browse_everything/templates/browse_everything_providers.yml.example
Under at least some versions of ruby you will get a:
/Users/jrochkind/.rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:97:in `find': Tried to load unspecified class: Symbol (Psych::DisallowedClass)
....
from /Users/jrochkind/.rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:302:in `safe_load'
from /Users/jrochkind/code/browse-everything/lib/browse_everything.rb:56:in `configure'
from having a raw symbol in Yaml. Commit a9ec7df0cfb10ea removed symbols
from yaml _keys_ in browse_everything_providers.yml.example, perhaps for this reason (or not, there are no relevant comments on commit), but retained the :signed_url as a value. Which still causes that safe Yaml error, safe yaml does not like symbols.
Changing it to a string seems to work fine, without causing that problem.
> example providers yaml should not use symbols

- lib/browse_everything/driver/s3.rb
- spec/unit/browse_everything/driver/s3_spec.rb
Some client code expects this, such as [sufia](https://github.com/samvera/sufia/blob/63e3f1338fb409b7854491ab3c9467209e009aa6/app/assets/javascripts/sufia/browse_everything.js) and (identical) [hyrax](https://github.com/samvera/hyrax/blob/0fe39d4f4dcc24deb805c1e66527ac^C9df7741a/app/assets/javascripts/hyrax/browse_everything.js).
In sufia/hyrax if the filename isn't there, it ends up blank in the UI.
I also added the expires header (where applicable), because I noticed that the [box driver](https://github.com/samvera/browse-everything/blob/2c0a3447049f7ee925a0ee0759d246fa28c474ac/lib/browse_everything/driver/box.rb#L59) has it, so I figured it couldn't hurt, although I am not aware of client code using it.
The sufia/hyrax client code REALLY wants a `size` key as well, but there doesn't …
> s3 driver includes file_name in link_for extras

- lib/browse_everything/retriever.rb
- spec/unit/browse_everything/retriever_spec.rb
For handling cases where `HTTParty` responses with status codes other than 200 (as this led to problems in which error messages from cloud providers were saved as binary file content)
> Implementing error handling for cases where HTTParty retrieves a response with a non-200 status code for downloads

- browse-everything.gemspec
- lib/browse_everything/retriever.rb
- spec/fixtures/vcr_cassettes/retriever.yml
- spec/lib/browse_everything/retriever_spec.rb
`BrowseEverything::Retriever` can experience out of memory errors when retrieving large files, even in chunked mode. `HTTParty`'s documentation clearly states that it's intended for small XML/JSON payloads and isn't designed for streaming. This PR replaces `HTTParty` with the much more robust and flexible [`Typhoeus`](https://github.com/typhoeus/typhoeus) HTTP library for improved speed and memory performance. The external interface to `BrowseEverything::Retriever` is unchanged.
> Replace HTTParty with Typhoeus for improved large file streaming support

- .gitignore
- browse-everything.gemspec
- lib/browse_everything.rb
- spec/fixtures/config/browse_everything_providers.yml
- spec/lib/browse_everything_spec.rb
Add shared config example to specs
> Allow browse_everything_providers.yml to contain symbols

- lib/browse_everything/driver/s3.rb
- spec/lib/browse_everything/driver/s3_spec.rb
> Ensures that the deprecated config. setting :signed_url for the S3 driver is properly mapped to a :response_type value, and defaults to :signed_url

- lib/browse_everything.rb
- spec/lib/browse_everything_spec.rb
Raise `BrowseEverything::ConfigurationError` if `browse_everything_providers.yml` is missing.
Fixes #247
> BrowseEverything::ConfigurationError for missing configuration yml

- browse-everything.gemspec
A Rails app is generated with a sass-rails dependency, so no changes to tests were needed -- the engine-cart-generated test app adds it's own sass-rails dependency.
While current Rails releases generate with sass-rails dependency, sass-rails is sunsetted/deprecated, due to the underlying pure-ruby ruby-sass gem being deprecated, and instructs "consider switching to the sassc gem"  https://github.com/sass/ruby-sass .
Rails 6.0 will perhaps depend on the sassc-rails gem instead, or perhaps the sass-rails gem itself will be changed to depend on sassc instead of sass-ruby. I am not sure if it is yet determined/done. https://github.com/rails/rails/issues/3289
But apps now may wish to switch to sassc-rails, especially if it's a new app. While sassc-rails _ought_ to be a drop-in replacement, …
> remove explicit sass-rails dependency

- .travis.yml
> Runs tests against Ruby releases 2.6.1, 2.5.3, 2.4.5, and 2.3.8 and ensures that Travis CI builds downgrade Bundler from 2.x releases

- .circleci/config.yml
- lib/browse_everything/driver/dropbox.rb
- lib/browse_everything/retriever.rb
- lib/generators/browse_everything/templates/browse_everything_providers.yml.example
- spec/lib/browse_everything/browser_spec.rb
- spec/lib/browse_everything/driver/dropbox_spec.rb
Currently, the Dropbox provider works by temporarily downloading the file from a remote storage server.  This file is created in a temporary location (please see https://github.com/samvera/browse-everything/blob/master/lib/browse_everything/driver/dropbox.rb#L94).
Unfortunately, in order to this to integrate with Hyrax, this directory must be explicitly whitelisted, leading to errors when using Dropbox to upload files for `FileSets`: https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/templates/config/initializers/hyrax.rb#L262
This also provides a configuration option for the Dropbox provider download directory path (as well as fixes the CircleCI config. for building the internal test app. using `engine_cart`).
> Ensures that Dropbox downloads are not placed within a directory outside of the Rails app

- LICENSE.txt
Applying GitHub-detectable version of apache license to be consistent with community standards.  
FWIW - I think this repository should have always been under Apache License.  It was created at a Hydra Partner event by folks who had Hydra iCLAs on file (and worked for institutions who had signed the Hydra MOU) which both indicate code would be contributed under Apache 2 licensing.
Initial meeting notes (browse-everything inception) https://wiki.duraspace.org/display/samvera/September+2013+Developer+Meeting+Agenda
iCLA Language
>This contributor license is an Apache Individual Contributor License Agreement v 2.0, see www.apache.org for more
information.
MOU Language
> All code contributed and accepted to the project will be distributed as open source software,
licensed under an Apache 2.0 …
> Apply Apache License

- .circleci/config.yml
- browse-everything.gemspec
- db/migrate/20190905134421_create_session_models.rb
- db/migrate/20190911121009_create_authorization_models.rb
- db/migrate/20190930132547_create_upload_models.rb
- db/migrate/20191004125901_create_upload_files.rb
This stabilizes the `next/rails-api/jrgriffiniii` branch with support for Rails 5.1.z releases.
> Supporting Rails 5.1.z releases

- browse-everything.gemspec
- lib/browse_everything/driver/dropbox.rb
Prior to this commit, the version restriction of Thor was locked to a
version compatable the various Rails versions, but reflective of the
somewhat implicit fixing pre 1.0 gem dependencies to a narrow version.
With the release of Thor 1.0 and Rails adherance to these ranges, this
commit opts for adding an explicit version range. _Note: We could
remove the explicit dependency, and allow for the upstream Rails
dependency to take effect._
Closes #338
> Easing version restriction of Thor

- browse-everything.gemspec
Based on further conversations on #338 and given that Thor is not
explicitly used in BrowseEverything, I'm removing the dependency.
BrowseEverything uses Rails Genarators (which use Thor), but we need
not worry ourselves with that.
> Removing explicit thor dependency

- browse-everything.gemspec
It's not actually a dependency of this gem; apps using this gem do not need puma installed, let alone a specific version of puma.
Past commit message at 0a9ed02 suggested puma was needed here for circle-ci to succeed, but let's see if that's still true.
Could resolve #337
> remove puma from .gemspec

- browse-everything.gemspec
In general, it's bad gem behavior to a lock to a very specific version. Prior, browse-everything was expressing the requirement that it would *only* work with googleauth 0.6.6. There is no way for a using app to use any older or any newer version, even if one comes out with a security patch etc.
0.6.6 is a pretty old version of googleauthi (Aug 2018, it's now up to 0.13), but browse-everything would not allow you to use a newer one. Which also meant that by transitive dependencies, you were stuck using faraday < 1.0 also, et al.
It is unfortunate that googleauth is still pre-1.0, so it's hard to count on semantic versioning. Still, looking at the [changelog](https://github.com/googleapis/google-auth-library-ruby/blob/master/CHANGELOG.md) of googleauth, it does not seem like any of the 0.x …
> Allow more recent googleauth

- browse-everything.gemspec
google_drive 3.0 came out November 2018. https://rubygems.org/gems/google_drive/versions/
Prior to this change, any app using browse_everything would be prevented from using google_drive 3.0.
The backwards compat changes in google_drive 3.0 appear minimal and only related to "google sheets", which I don't believe browse_everything uses, so I believe it should Just Work to allow google_drive 3.0. If not, hopefully tests will catch it?
https://github.com/gimite/google-drive-ruby/blob/master/MIGRATING.md#migrating-from-version-2xx
> Allow google_drive 3.x

- .circleci/config.yml
- README.md
- app/jobs/browse_everything/upload_job.rb
Resolve duplicate id errors in downstream use
> Remove support for rails 5.1, rely on ActiveStorage id generation

- app/controllers/browse_everything/uploads_controller.rb
- app/jobs/browse_everything/upload_job.rb
- app/models/browse_everything/upload_file.rb
- db/migrate/20200423125901_add_file_attrs_upload_files.rb
- lib/browse_everything/upload.rb
> Ensures that File System uploads are no longer dependent upon ActiveStorage and provides ActiveStorage cleaning

- .circleci/config.yml
- browse-everything.gemspec
Testing removing the sprockets dependency as a first step to understanding and resolving #310 and the PRs: #311 and #345.
In the circleci config it runs bundle install when it has just checked out the code so it pulls in sprockets 4 (or gets it from cache). Then it does engine cart and the rails version might pin it to an earlier version of sprockets there. But after the engine cart generation there's another bundle install which is where the error was happening. So if we precede that with a sprockets upgrade everything seems to work fine. This should now be caching so it shouldn't slow things down, but maybe we want to look at caching more down the line.
> Remove sprockets dependency

- browse-everything.gemspec
The `google_drive` gem does not seem to actually be used. I can't find it used anywhere, and tests still pass without it.
We do currently use `google-api-client`, that's what's actually used for connecting to google drive storage.  I think it's a mistake that this is still in gemspec. 
See also #363
> remove unused google_drive gem dependency

- browse-everything.gemspec
google-api-client is deprecated. Closes #363
> Swap google-api-client for more specific smaller-size gem google-apis-drive_v3

- browse-everything.gemspec
That is now taken care of by google-apis-drive_v3. Having both of them as dependencies is bad, and results in them both trying to supply some of the same classes. This is what #365 was meant to do, but it got corrupted somehow.
> Remove google-api-client dependency

- app/assets/javascripts/browse_everything.js
according to the `bootstrap` rubygem docs:
> While bootstrap-sprockets provides individual Bootstrap components for ease of
> debugging, you may alternatively require the concatenated bootstrap for faster
> compilation
this gem shouldn't force the debugging features on downstream apps.
this is motivated in part by error like this occuring during a bootstrap
upgrade in Hyrax:
> Sprockets::FileNotFound: couldn't find file 'bootstrap-sprockets' with type
> 'application/javascript'
> require 'bootstrap' javascript instead of 'bootstrap-sprockets'

- browse-everything.gemspec
- lib/browse_everything/driver/dropbox.rb
dropbox_api 0.1.20 changed the internals of DropboxApi::Authenticator such that calls to get_token and authorize_url
are no longer forwarded to an OAuth2::Strategy::AuthCode instance.  Fixing compatibility required calling these methods
on Authenticator#auth_code.
See https://github.com/Jesus/dropbox_api/pull/88
> Fix compatibility with dropbox_api 0.1.20+ and force upgrade

- app/assets/javascripts/browse_everything/behavior.js
- lib/browse_everything/driver/dropbox.rb
- spec/features/select_files_spec.rb
This rebases and deprecates #375 (which @dlpierce alone authored):
> Opening and selecting directories containing 1000s of files is slow due to excessive interaction with the DOM. This tracks which files are selected in a map and only appends the resulting input objects when the browse everything dialog is submitted.
>
> Some performance numbers: Previously, simply checking the Select All box on an already expanded file system directory containing 12000 files would take close to 10 minutes to complete. This now completes in about 5 seconds, and then submitting the form takes 30s. (There could be further optimization here.)
Additionally, this also temporarily disables the Turbolinks test suite blocking the merging of pull requests.
> Speed up file selection by avoiding unnecessary DOM interaction

- .circleci/config.yml
- .tool-versions
- Gemfile
- browse-everything.gemspec
- spec/features/test_compiling_stylesheets_spec.rb
- spec/javascripts/karma_spec.rb
Resolves #379, and also addresses the following:
- Updating the CircleCI config. for the latest release of Ruby 2.6 and 2.7, and Rails 5.2 and 6.0
- Updating the engine_cart release dependency
> Disables the unstable test suites for the JavaScript (using `karma`) and stylesheet compilation

- browse-everything.gemspec
- lib/browse_everything/driver/base.rb
bixby includes rubocop version dependencies. I was having trouble even getting tests to run locally without this, and it's a pre-requisite for work to add support for more ruby/rails versions, I think.
Fixed one issue with calling `super` in `inherited` that new version of bixby/rubocop caught and required fixing to build!
> update bixby to latest release

- .circleci/config.yml
- README.md
* Remove ruby 2.5 support, the new orb switches to `cimg` circleci ruby images that do not support ruby 2.5
* 2.4 had been dropped from CI at some point in the past, but was still mentioned in README. Rectified. 
* Switch from deprecated samvera orb `bundle_for_gem` command to preferred `bundle` command.
* Remove the SECOND/DOUBLE `bundle_for_gem` action in config.yml, not sure what it was doing there, we seem to be green without it.
> update samvera/circleci-orb to 1.x

- .circleci/config.yml
We think rails 6.0.3+ does support ruby 3.0 but not ruby 3.1. https://buildkite.com/rails/rails/builds/87101
Rails earlier than 6.0 does not support ruby 3.0, should not be tested with it.
Closes #373 and replaces #385
> CI Build with rails 6.0 and ruby 3.0

- .circleci/config.yml
- README.md
- lib/browse_everything.rb
- spec/test_app_templates/Gemfile.extra
* Requires some Gemfile.extra business to get engine_cart to succesfully create a rails 6.1/ruby 3.1 project prior to `mail` gem 2.8.0 being released. https://bibwild.wordpress.com/2022/06/13/using-engine_cart-with-rails-6-1-and-ruby-3-1/
* Then we run into an actual 3.1 failure, with removal of deprecated method args for `YAML.safe_load`, need to use new non-deprecated form of arg.  New non-deprecated form is available as of ruby 2.6 -- and we already dropped ruby 2.5 from support/CI build matrix in #395 , so we're good without a conditional! 
* Closes #389
> Rails 6.1 ruby 3.1

- .circleci/config.yml
- .rubocop.yml
- Gemfile
- README.md
- browse-everything.gemspec
- lib/browse_everything/engine.rb
Or at least build passes -- actually getting your CSS and JS loaded in a real Rails 7 app would require some not totally documented steps, but that's really an existing problem that applies to Rails 6.1  (and possibly earlier) too, unfortunately, a separate problem. 
Minimal actual code changes were required to get build to pass on Rails 7. 
- allow Rails 7 in gemspec
- don't try to configure sprockets if sprockets not included in app
- sprockets-rails is now optional for rails 7. Without it... not totally sure how you're going to get b-e CSS and JS to load, but let's at least let you try by not crashing. (The test setup is at least trying to include JS with Webpacker somehow...)
- Opt into rspec-rails 6.0.0.rc1 for Rails 7 compat
- Test circleci under rails 7, ruby 3.1
> Support for Rails 7.0

- app/assets/javascripts/browse_everything/behavior.js
- spec/support/app/views/file_handler/index.html.erb
- spec/support/app/views/file_handler/main.html.erb
- spec/test_app_templates/lib/generators/test_app_generator.rb
While CI isn't currently running JS feature tests (working on it in #400), I _am_ able to run them locally (and have them be green -- both before and after this PR).  These fixes came from such, as well as from manually running the engine_cart `.internal_test_app` and manipulating it in manual tests. 
Feature tests [tried to test a "No Turbolinks" test path](https://github.com/samvera/browse-everything/blob/35b4e3cd1a6fd10f79bcfd3d4cebc9fe4d3ebe89/spec/features/select_files_spec.rb#L34), by [clicking on a link with "data-no-turbolink" attribute](https://github.com/samvera/browse-everything/blob/35b4e3cd1a6fd10f79bcfd3d4cebc9fe4d3ebe89/spec/support/app/views/file_handler/index.html.erb#L4)
Two problems with this:
1. That attribute has no effect on recent versions of Turbolinks that were …
> Tweak some javascript problems

- README.md
- spec/features/select_files_spec.rb
- spec/features/test_compiling_stylesheets_spec.rb
This is necessary in order to request from the community renewed efforts for maintenance, and to direct those outside of the community to the Samvera Slack.
> Updating the Product Owner information in preparation for the 2022 autumn request for maintenance

- .circleci/config.yml
Locally tests passed under Rails 7.0 and Ruby 3.2 with no changes to code.
> Run CI with Ruby 3.2

- spec/lib/browse_everything/auth/google/credentials_spec.rb
Something has changed in dependencies such that test results are different, I don't believe it effects functionality, but also am not sure google oauth actually works at all, can't say personally.
> make google oauth tests pass again

- browse-everything.gemspec
- lib/browse_everything/auth/google/request_parameters.rb
- lib/browse_everything/driver/base.rb
Several accumulated test setup things were preventing green CI.  In some cases I don't really understand how CI used to pass but stopped with no code changes, but these changes all make sense. 
Don't know exactly how this got in main branch, but currently failing build due to:
```
lib/browse_everything/driver/base.rb:72:19: C: [Correctable] Style/RedundantParentheses: Don't use parentheses around a logical expression.
@name ||= (@config[:name] || self.class.name.split(/::/).last.titleize)
```
Again can't explain why this passed CI at some previous point but stopped, but was getting errors with:
```
NameError:
uninitialized constant BrowseEverything::Auth::Google::OpenStruct
```
Fixed with `require 'ostruct'` and changing reference to explicit top-level `::OpenStruct`. 
sqlite3 ruby gem …
> Fix CI setup

- .circleci/config.yml
- .tool-versions
Updating the tool versions and removing Ruby releases prior to 3.1 and Rails releases 6.1. Ensuring that NodeJS is support is limited to LTS Gallium and bundler 2.5.21
> Updating the tool versions and removing Ruby releases prior to 3.1 and Rails releases 6.1

- Gemfile
- README.md
- browse-everything.gemspec
This life-support level of maintenance fix will test in Rails 8 only **by using sprockets**, even though `rails new` won't generate an app with sprockets. (You CAN still use sprockets with Rails 8). 
This is not a good fix, it's really life-support only. But this gem has been getting little maintainance, interest, or use. 
It will be accompanied by a README fix explainig present state of app, and how some (me) are working around to use without sprockets (copy all jS and CSS locally into app).
> Allow and Test in Rails 8, super hackily
