samvera/browse-everything

lib/browse_everything/engine.rb, spec/views/browse_everything/_file.html.erb_spec.rb
This is causing failures in Sufia and any other application that uses this gem under Rails 4.2.
=> Fix asset path configuration, #94

lib/browse_everything/retriever.rb
=> Fixes typo in BrowserEverything::Retriever#retriever.

lib/browse_everything/driver/box.rb, spec/fixtures/vcr_cassettes/dropbox.yml
Fix minor issues in Dropbox and Box API providers to account for recent implementation changes
=> Driver fixes

app/assets/javascripts/browse_everything/behavior.js.coffee
Fixes psu-stewardship/archivesphere#183 which we ran into because of recent changes enabling recursive selecting of directories.
=> Add .ev-select-all to event listener, fixes #109

app/controllers/browse_everything_controller.rb, spec/fixtures/vcr_cassettes/dropbox.yml, spec/helper/browse_everything_controller_helper_spec.rb, spec/unit/dropbox_spec.rb
=> Fixing dropbox integration

Gemfile, Rakefile, browse-everything.gemspec, spec/features/select_files_spec.rb, spec/spec_helper.rb, spec/support/app/views/file_handler/main.html.erb
Updates the testing environment and adds an integration test using Poltergeist. This should catch the problem we were seeing last week where callbacks were not occurring due to an update in Rails.
=> Test updates

browse-everything.gemspec, lib/browse_everything/retriever.rb
=> Require addressable and call it from the root

app/assets/javascripts/browse_everything/behavior.js.coffee, app/views/browse_everything/_file.html.erb, spec/features/select_files_spec.rb
Allows you to select a file by using a checkbox, the same way you would select a directory of files.
=> Enable checkbox selection for files

app/assets/stylesheets/browse_everything/_browse_everything.scss
Before:
After:
@cam156 I updated the css to remove the check icon.
=> Remove extraneous check icons for selected files

Gemfile, app/views/browse_everything/_file.html.erb, spec/test_app_templates/Gemfile.extra, spec/test_app_templates/lib/generators/test_app_generator.rb, spec/views/browse_everything/_file.html.erb_spec.rb
This fixes a problem documented in https://github.com/psu-stewardship/scholarsphere/issues/834
=> Long filenames

README.md
Fixes the mailing list address and updates some other links to target `samvera` locations.
Also fixes a reference to Questioning Authority, which seems to just be in error.
=> Update README.md for Samvera

.rubocop.yml, lib/browse_everything/driver/google_drive.rb, spec/fixtures/vcr_cassettes/google_drive.yml, spec/helper/browse_everything_controller_helper_spec.rb, spec/unit/google_drive_spec.rb
=> Extends the tests for the Google Drive provider and resolves the web_content_link issue

.rubocop.yml, browse-everything.gemspec, lib/browse_everything/driver/dropbox.rb, spec/fixtures/vcr_cassettes/dropbox.yml, spec/spec_helper.rb, spec/unit/browser_spec.rb, spec/unit/dropbox_spec.rb
Resolves #159 by providing compliance with v. 2 of the web API
=> Updates the Dropbox Provider to use the dropbox_api Gem

app/controllers/browse_everything_controller.rb, lib/browse_everything/driver/base.rb, lib/browse_everything/driver/google_drive.rb, spec/fixtures/vcr_cassettes/google_drive.yml, spec/unit/google_drive_spec.rb
As first identified by @scherztc , there appear to be cases where authentication fails when attempting to pass an OAuth2 access token to the API for Google Drive
=> [WIP] Resolving issues relating to Google API access token authentication

.travis.yml, app/assets/javascripts/browse_everything/behavior.js.coffee, browse-everything.gemspec, spec/spec_helper.rb, spec/support/capybara.rb
=> Restructures the Travis CI config, fully deprecates PhantomJS, resolves Turbolinks test errors for Rails 5.0.x releases

config/routes.rb, lib/browse_everything/driver/file_system.rb
Progresses towards resolving #204
=> Ensures that file and directory paths containing "." characters resolve

.rubocop.yml, lib/browse_everything.rb, lib/browse_everything/driver/authentication_factory.rb, lib/browse_everything/driver/base.rb, lib/browse_everything/driver/box.rb, lib/browse_everything/driver/dropbox.rb, lib/browse_everything/driver/file_system.rb, lib/browse_everything/driver/google_drive.rb, lib/browse_everything/driver/s3.rb, spec/unit/browse_everything/driver/google_drive_spec.rb
=> Provides a sorting lambda for drivers and Module methods for mutating and setting sorter Procs for BrowseEverything::Driver

browse-everything.gemspec, lib/browse_everything/auth/google/request_parameters.rb
=> Integrates support for Google Team Drives

app/controllers/browse_everything_controller.rb, app/views/browse_everything/_files.html.erb, app/views/browse_everything/index.html.erb, lib/browse_everything/driver/base.rb, lib/browse_everything/driver/box.rb, lib/browse_everything/driver/dropbox.rb, lib/browse_everything/driver/google_drive.rb, lib/generators/browse_everything/templates/browse_everything_providers.yml.example, spec/controllers/browse_everything_controller_spec.rb, spec/lib/browse_everything/driver/dropbox_spec.rb
- Fixes Dropbox authentication and authorization with OAuth2
- Ensures that `nil` file `size` and `mtime` metadata is handled
- Fixes Dropbox directory browsing
=> Bug fixes for Dropbox authentication and file browsing

lib/browse_everything/version.rb
Issues the first candidate for a 1.0.0 release.
=> Release version 1.0.0.RC1

app/assets/javascripts/browse_everything/behavior.js
IF converting to straight ES5 is considered a suitable resolution to #257, here's one try.
This was just auto-converted using babel. From the source already auto-converted from coffeescript to ES6.
Not sure if we're doing something abominable here or resulting in code that is going to be hard for humans to edit... but it looks relatively readable to me, at least as readable as what was there before, which may not have been very readable. 
I first tried manually converting, but there was just too much. 
I have verified this gets through uglifier. It also passes all automated tests; not sure if the tests are enough to make us confident it's good?
=> convert to ES5

.circleci/config.yml, browse-everything.gemspec
Builds can be parallelized using the free service tier: https://circleci.com/gh/jrgriffiniii/browse-everything/23
=> Adds the configuration for integration with CircleCI

.gitignore, app/views/browse_everything/_files.html.erb, browse-everything.gemspec, lib/browse_everything/driver/box.rb, lib/browse_everything/driver/dropbox.rb, lib/browse_everything/driver/file_system.rb, lib/browse_everything/driver/google_drive.rb, lib/browse_everything/driver/s3.rb
This resolves issues I've discovered when testing against https://github.com/samvera/hyrax/releases/tag/v3.0.0.pre.beta2 using the following providers:
- File System
- Dropbox
- Google Drive
- S3
Following the testing of the Box provider, this should prepare for a 1.0.1 release, and the changes in https://github.com/samvera/hyrax/compare/master...jrgriffiniii:hyrax3-plus-be1.0-jrgriffiniii should be introduced.
=> Support the Hyrax 3.0.0 beta 2 pre-release

lib/browse_everything/version.rb
Offers a new release with the changes introduced in https://github.com/samvera/browse-everything/pull/270
=> Updating the release version to 1.0.1

README.md
=> Adds the CircleCI status badge to the README

.circleci/config.yml, README.md
Re: samvera/maintenance#20
Re: samvera/maintenance#21
=> Tidy up CircleCI / README regarding Ruby/Rails versions

.circleci/config.yml
Re: samvera/maintenance#20
Re: samvera/maintenance#21
=> Unroll CircleCI ruby/rails versions; remove defaults

app/controllers/browse_everything/containers_controller.rb, app/controllers/browse_everything/providers_controller.rb, app/controllers/concerns/browse_everything/controller/authorizable.rb, app/jobs/upload_job.rb, app/serializers/provider_serializer.rb, lib/browse_everything/provider.rb, lib/browse_everything/provider/file_system.rb, lib/browse_everything/provider/google_drive.rb
This addresses some bugs discovered while testing during Samvera Connect 2019
=> Introduces support for a `file_system` driver for the 2.0 prototype

README.md, browse-everything.gemspec, lib/generators/browse_everything/install_generator.rb, lib/generators/browse_everything/templates/Procfile, lib/generators/browse_everything/templates/app/javascript/packs/browse_everything.jsx, lib/generators/browse_everything/templates/config/webpack/development.js, lib/generators/browse_everything/templates/package.json, spec/support/app/controllers/file_handler_controller.rb, spec/support/app/views/file_handler/index.html.erb, spec/test_app_templates/lib/generators/test_app_generator.rb
Advances #327, but blocked by https://github.com/samvera-labs/browse-everything-redux-react/pull/36
=> Provides an initial attempt at integrating the React UI with the Rails server for testing

app/models/browse_everything/authorization_model.rb, app/models/browse_everything/session_model.rb, app/models/browse_everything/upload_file.rb, app/models/browse_everything/upload_model.rb, db/migrate/20190905134421_create_session_models.rb, db/migrate/20190911121009_create_authorization_models.rb, db/migrate/20190930132547_create_upload_models.rb, db/migrate/20191004125901_create_upload_files.rb, lib/browse_everything/authorization.rb
To resolve missing table error in development environment for downstream app
=> Namespace classes referenced by BrowseEverything::Authorization

app/models/browse_everything/authorization_model.rb, app/models/browse_everything/session_model.rb, app/models/browse_everything/upload_file.rb, app/models/browse_everything/upload_model.rb, lib/browse_everything/authorization.rb
=> Specify table name in models to match migration

.circleci/config.yml, .rubocop.yml, Gemfile, app/assets/javascripts/browse_everything/behavior.js, app/assets/javascripts/treetable.webpack.js, app/controllers/browse_everything_controller.rb, app/helpers/browse_everything_helper.rb, app/views/browse_everything/_files.html.erb, browse-everything.gemspec, lib/browse_everything/auth/google/credentials.rb, lib/browse_everything/auth/google/request_parameters.rb, lib/browse_everything/browser.rb, lib/browse_everything/driver/base.rb, lib/browse_everything/driver/box.rb, lib/browse_everything/driver/dropbox.rb, lib/browse_everything/driver/file_system.rb, lib/browse_everything/driver/google_drive.rb, lib/browse_everything/driver/s3.rb, lib/browse_everything/file_entry.rb, lib/browse_everything/retriever.rb, spec/features/test_compiling_stylesheets_spec.rb, spec/lib/browse_everything/driver_spec.rb, spec/spec_helper.rb, spec/test_app_templates/Gemfile.extra, spec/test_app_templates/lib/generators/test_app_generator.rb
Resolves #315 and #316 by adding Ruby 2.7, adding Rails 6.0.2, and updating the existing Ruby and Rails releases on the CircleCI config.
=> Adds Ruby 2.7 and Rails 6.0.2 to the CircleCI config.

lib/browse_everything/version.rb
=> Release 1.1.2

.circleci/config.yml, lib/browse_everything/driver/dropbox.rb, spec/features/select_files_spec.rb
Fixes #369
This PR adds the Circle CI step that fails if the branch name is master.
=> Adds Circle CI step that fails if branch name is master

.circleci/config.yml, README.md
=> add Rails 6.1 with ruby 3.0 to CI Build

README.md
* disclosure to those using or looking at using gem as to current state
* outline suggestion of a development agenda to anyone looking to do more work on it in the future
=> Add some transparency to README about current limitations

.circleci/config.yml, lib/browse_everything/version.rb
This version will work with Rails 8.0 (sort of, see README)
=> bump version in prep for 1.5.0 release
